baseURL = "https://hyesunyun.github.io/recipe-book/"
relativeURLs = true
canonifyurls = true
languageCode = "en-us"
title = "Bison's Recipe Book"
theme = "recipes"

[params]
  author = "Bison Yun"
  description = "Bison's Recipe Book"